[package]
name = "tracy"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
failure = "0.1.5"
quickcheck = "0.8.2"
quickcheck_macros = "0.8"
rayon = "1.0.3"
